### ISSUE TITLE
External dataset

### ISSUE THREAD

**Issue by zyannick** [cicese-biocom/esm-AxP-GDL#14]
Hi, 
I hope that you're doing well.
In the paper you're talking about external dataset. Is it this one?
datasets/AMPDiscover/External.csv
Just for fair comparison with you method  (in this paper **_Predicting Antimicrobial Peptides Using ESMFold-Predicted Structures andESM-2-Based Amino Acid Features with Graph Deep Learning_**), do you train, validate and test your methods on this dataset here:

![image](https://github.com/user-attachments/assets/f2647652-6f9b-44eb-aa29-e3d025cbff5c)

and here:

![image](https://github.com/user-attachments/assets/e834043c-0bbf-4d9f-aa51-542a5fa361af)

**Comment by cicese-biocom** [comment]
Hi,
The models were trained, validated and tested using the [AMPDiscover(Training-Validation-Test).csv](https://github.com/cicese-biocom/esm-AxP-GDL/blob/main/datasets/AMPDiscover/AMPDiscover(Training-Validation-Test).csv). The results on the test set are shown in Table 2.

The external set was used to assess the best models built with the dataset aforementioned. The results on the external set are shown in Table 3. Additionally, the models were combined to improve the prediction on the external set. The results are shown in Table 4.

Best regards,
Cesar
