### ISSUE TITLE
Other downstream task usage?

### ISSUE THREAD

**Issue by BIOBRICK** [cicese-biocom/esm-AxP-GDL#9]
Very impressive work! Congratulations!

Here I wish to ask, **wether this framework can be used into other kinds of tasks**? Such as enzymatic activity prediction? Because I think here you have presented a universial protein frame without any pre-request. Such kind of network can be used on any kind of protein-related tasks.

For example, I get a dataset containing AA sequences (proteins actually), and have multiple labels for their enzymatic activities for various substance, like H2O2、Sugar or any other things. The protein are classified as 0/1 wether they can catalyze their decomposition. I have tried a lot of solutions and I can't get a good model for my problem. Can I use my dataset to re-train your model and used it on my own task? (with some modifications maybe?)

**Comment by cicese-biocom** [comment]
Many thanks for your comment about our work!

This framework can be applied for modeling any kind of task other than the antimicrobial peptide classification. However, it is not required to re-train our models. In your case, a new model might be built from scratch using the best settings suggested by us (see train.sh script for an example), or using settings specified by you according to the characteristics of your dataset. 

Moreover, we also created a KNIME workflow to automatically built binary classification models by applying 30 feature selectors, 10 individual classifiers, and 4 ensemble classifiers. This framework and results were published at https://onlinelibrary.wiley.com/doi/10.1002/pro.4928.

Best regards,

**Comment by BIOBRICK** [comment]
> 非常感谢您对我们工作的评论！
> 
> 该框架可用于模拟除抗菌肽分类以外的任何类型的任务。但是，不需要重新训练我们的模型。在您的情况下，可以使用我们建议的最佳设置（有关示例，请参阅 train.sh 脚本）或使用您根据数据集的特征指定的设置从头开始构建新模型。
> 
> 此外，我们还创建了一个 KNIME 工作流程，通过应用 30 个特征选择器、10 个独立分类器和 4 个集成分类器来自动构建二元分类模型。该框架和结果发表在 [https://onlinelibrary.wiley.com/doi/10.1002/pro.4928[](https://www.sci-hub.ee/10.1002/pro.4928)](https://onlinelibrary.wiley.com/doi/10.1002/pro.4928)。
> 
> 此致敬意

Many thanks! I'll try it on my work. Thanks again for presenting such an awsome job!
